### ISSUE TITLE
Swift on Server Guides links are 404

### ISSUE THREAD

**Issue by marcblanchet** [apple/swift-org-website#111]
## Describe the bug

Swift on Server Guides links are 404

## To Reproduce

1. Go to [Swift on Server Guides](https://www.swift.org/server/guides/)
2. Click on [Setup and code editing](https://swift.org/server/guides/setup-and-ide-alternatives/)
3. See error404

## Expected behavior

Should have the guide displayed 

## Actual behavior

HTTP 404 file not found

**Comment by 0xTim** [comment]
Eurgh I'm guessing this is a web server difference to running it locally when I tested the PR and what's in live. Thanks for reporting! I'll work out how to fix it

**Comment by alexandersandberg** [comment]
Thanks for reporting this issue, @marcblanchet! A fix is now live. 🙂
