### ISSUE TITLE
Swift trainning question error

### ISSUE THREAD

**Issue by aimore** [apple/swift-org-website#164]
## Describe the bug
On the swift tutorials website one question seems to be wrong
https://developer.apple.com/tutorials/app-dev-training/displaying-data-in-a-list

## To Reproduce
go to website 
https://developer.apple.com/tutorials/app-dev-training/displaying-data-in-a-list and the wrong answer will be displayed

## Expected behavior
 ForEach(namedFonts) { namedFont in
        Text(namedFont.name)
    }

## Actual behavior
ForEach(sessions, id: \.sessionNumber) { session in
    Text(session.title)
}

## Screenshots
<img width="937" alt="Screen Shot 2022-10-18 at 11 56 20 am" src="https://user-images.githubusercontent.com/8807639/196310897-5b321a0c-65a0-4ce9-8cd5-dcde9a53e373.png">

**Comment by alexandersandberg** [comment]
The issues on this repo are only for content on Swift.org.

[developer.apple.com](https://developer.apple.com) is separate website. You can submit feedback to them via [Feedback Assistant](https://developer.apple.com/bug-reporting/).

---

But to answer your question, I believe the answer you got is correct. Unless the items passed to `ForEach` conform to `Identifiable`, an `id` is required.
