### ISSUE TITLE
Dark mode for documentation page

### ISSUE THREAD

**Issue by UniverseFly** [apple/swift-org-website#196]
I am not sure if it is a bug or a feature request but it seems the [documentation website](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html) only supports light mode, even if the homepage does support dark mode.

**Comment by wazawoo** [comment]
I would love to help with this! Super unsure of where to start though (I'm guessing it isn't done yet because there's something funky about that part of swift.org)

**Comment by alexandersandberg** [comment]
Closing this as TSPL gained dark mode support when it was [converted to DocC](https://www.swift.org/blog/tspl-on-docc/). 🙂
