### ISSUE TITLE
Drop using gumshoe.min.js if possible

### ISSUE THREAD

**Issue by shahmishal** [apple/swift-org-website#212]
We are currently using gumshoe.min.js 3.x version for toggling menu, if possible we should replace this logic. 

https://github.com/apple/swift-org-website/blob/main/assets/javascripts/application.js#L8

**Comment by ishaanbedi** [comment]
Hi @shahmishal & fellow contributors! To be more clear about what I understood from this issue, we are planning to drop the usage of gumshoe from swift.org website and implement the logic using vanilla javascript only, right?
I'd like to work on this issue. Can I start working on it?

**Comment by 0xTim** [comment]
@ishaanbedi go for it!

**Comment by ishaanbedi** [comment]
Hi @0xTim ! I've raised a pull request #215 that fixes this issue. Can you please have a look over it?
