### ISSUE TITLE
[SR-11230] Swift.org community server writing typos

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-org-website#219]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11230      |
   |Radar             | None         |
   |Original Reporter | jayvenn (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

<https://swift.org/community/#communication>

Typo \#1 can be found under the Forums/Announcements.

Typo \#2 can be found under the Forums/Server.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Project Infrastructure    |
   |Labels            | Bug, Website        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 8771b41f95b5c9dbfeac4783dc1a2367

  </details>

**Issue Description:**

Propose changes:

1\.

For announcements relevant to developers such as release **announcments**, branching, and infrastructure updates.

-\>

For announcements relevant to developers such as release **announcements**, branching, and infrastructure updates.

 

2\.

For developers to discuss **erver** focused capabilities supported by Swift.org and the Server work group.

-\>

For developers to discuss **server** focused capabilities supported by Swift.org and the Server work group.

**Comment by alexandersandberg** [comment]
These typos have already been fixed.
