### ISSUE TITLE
[SR-3778] Linux Swift installation instructions need a minor update

### ISSUE THREAD

**Issue by heckj** [apple/swift-org-website#220]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3778      |
   |Radar             | None         |
   |Original Reporter | @heckj      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Ubuntu 16.04  
swift 3.1 development snapshot installed  
Vagrant virtual machine  
(explicit setup at <https://github.com/heckj/vagrant-ubuntu-swift-dev)>

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       |     |
   |Labels            | Bug, Website        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 6dcb718323ce3ab0e52377f49bc1840c

  </details>

**Issue Description:**

at <https://swift.org/download/#using-downloads> under the Linux instructions, the first step reports a couple of dependencies that need to be installed:

-   \`sudo apt-get install clang libicu-dev\`

With the 3.1 swift snapshot, those dependencies are necessary but not sufficient, also requiring python-dev to utilize swift REPL from the installation, at least on Ubuntu 16.04.

The updated line should read:

-   \`sudo apt-get install clang libicu-dev python-dev\`

**Comment by tomerd** [comment]
this looks to be 6 years old, and referring to swift 3.1 and ubuntu 16.04. should we close it?

**Comment by alexandersandberg** [comment]
Yeah, these installation instructions no longer exist anyway. 👍
