### ISSUE TITLE
[SR-1987] Link to "Swift standard library changes" in blog post "Swift 3 API Design Guidelines" is a 404

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-org-website#223]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1987      |
   |Radar             | None         |
   |Original Reporter | marcpalmer (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Project Infrastructure    |
   |Labels            | Bug, Website        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 99390014b5aafe71c5d839940afe96e8

  </details>

**Issue Description:**

The link in the "Swift 3 API Design Guidelines" blog post at <https://swift.org/blog/swift-3-api-design/> is to <https://github.com/apple/swift/tree/swift-3-api-guidelines> but that is 404.

**Comment by alexandersandberg** [comment]
As this blog post is from December 2015, I would say it's fine to just close this issue and not worry about the 404 caused by a missing branch.

**Comment by shahmishal** [comment]
The branch is now restored and link works.

**Comment by MaxDesiatov** [comment]
Can that branch also be made protected so that it isn't deleted again?

**Comment by shahmishal** [comment]
Yes, I added rule already to do this.
