### ISSUE TITLE
Update `memcached client` project details

### ISSUE THREAD

**Issue by shehabadel** [apple/swift-org-website#255]
## Is your feature request related to a problem? Please describe

The binary protocol mentioned in `memcached client` project in [GSoC 2023](https://www.swift.org/gsoc2023/) is actually deprecated.  

## Describe the solution you'd like

After mentioning the issue to @FranzBusch on Swift-Forum [here](https://forums.swift.org/t/interested-in-memcached-client-project/63549/5),  I think we should consider changing the project description to implement memcached client following `ASCII Protocol` instead of the `Binary protocol`, and add the following [documentation](https://github.com/memcached/memcached/blob/master/doc/protocol.txt).

**Comment by FranzBusch** [comment]
We should change the description to say we need to implement the `Meta command protocol`

**Comment by alexandersandberg** [comment]
I mentioned it in the linked PR as well, but is https://github.com/memcached/memcached/wiki/MetaCommands maybe a better link to refer to than https://github.com/memcached/memcached/blob/master/doc/protocol.txt?

**Comment by shehabadel** [comment]
> I mentioned it in the linked PR as well, but is https://github.com/memcached/memcached/wiki/MetaCommands maybe a better link to refer to than https://github.com/memcached/memcached/blob/master/doc/protocol.txt?

> The full description of the Meta commands are available in the Text Protocol documentation:
[Text Protocol](http://github.com/memcached/memcached/blob/master/doc/protocol.txt)
This wiki serves as a companion to protocol.txt with use cases and examples of the new commands.

I think the protocol.txt link is more descriptive and has more details than MetaCommands. However, I think we should add both 😃

**Comment by shilpeegupta14** [comment]
@alexandersandberg  Even I was thinking we should use both the links such that "Meta protocol" will link to https://github.com/memcached/memcached/blob/master/doc/protocol.txt and "Commands" will link to https://github.com/memcached/memcached/wiki/MetaCommands 

Shall I change or is the current status good?

**Comment by alexandersandberg** [comment]
I would try to keep it to one link rather than two, if possible. Those who want to learn more should be able to do so though. 

This is why I was suggesting linking to https://github.com/memcached/memcached/wiki/MetaCommands instead, as it's more focused on the meta commands protocol, and the protocol.txt link can be found on that page as well—for those who want to learn more.

But this is just my suggestion. As @FranzBusch is a potential mentor of the project, I would prioritize his feedback. 🙂

**Comment by FranzBusch** [comment]
@alexandersandberg Let's stick with the link to the wiki. That is the better intro and it refers to the other link as well.
