### ISSUE TITLE
Searching for "Feature Identifier" on swift.org/swift-evolution

### ISSUE THREAD

**Issue by MarcoEidinger** [apple/swift-org-website#261]
## Is your feature request related to a problem? Please describe

Proposals may have a new, optional field that defines the feature identifier that allows for [Piecemeal adoption of upcoming language improvements](https://github.com/apple/swift-evolution/blob/cf8419c15503dc2384b469c29b64c20bc905ea6c/proposals/0362-piecemeal-future-features.md)

Unfortunately, it is not possible to search for proposals that have a feature identifier. It is also not possible to search for a proposal with a given feature identifier. 

## Describe the solution you'd like

- Being able to search and find proposals that have a "Feature Identifier" (a.k.a. upcoming feature flag)
- Being able to search and find a proposal for a given Feature Identifier

## Additional context

Excerpt from [Proposals define their own feature identifier ](https://github.com/apple/swift-evolution/blob/cf8419c15503dc2384b469c29b64c20bc905ea6c/proposals/0362-piecemeal-future-features.md#proposals-define-their-own-feature-identifier)

> [Swift proposal template](https://github.com/apple/swift-evolution/blob/main/proposal-templates/0000-swift-template.md) got amended with a new, optional field that defines the feature identifier:

> **Feature identifier**: UpperCamelCaseFeatureName
> Amend the following proposals, which are partially or wholly delayed until Swift 6, with the following feature identifiers:

> Several proposals were amended to mention the respective feature identifier

> * [SE-0274 "Concise magic file names"](https://github.com/apple/swift-evolution/blob/main/proposals/0274-magic-file.md) (`ConciseMagicFile`) delayed the semantic change to `#file` until Swift 6. Enabling this feature changes `#file` to mean `#fileID` rather than `#filePath`.
> * [SE-0286 "Forward-scan matching for trailing closures"](https://github.com/apple/swift-evolution/blob/main/proposals/0286-forward-scan-trailing-closures.md) (`ForwardTrailingClosures`) delays the removal of the "backward-scan matching" rule of trailing closures until Swift 6. Enabling this feature removes the backward-scan matching rule.
> * [SE-0335 "Introduce existential `any`"](https://github.com/apple/swift-evolution/blob/main/proposals/0335-existential-any.md) (`ExistentialAny`) delays the requirement to use `any` for all existentials until Swift 6. Enabling this feature requires `any` for existential types.
> * [SE-0337 "Incremental migration to concurrency checking"](https://github.com/apple/swift-evolution/blob/main/proposals/0337-support-incremental-migration-to-concurrency-checking.md) (`StrictConcurrency`) delays some checking of the concurrency model to Swift 6 (with a flag to opt in to warnings about it in Swift 5.x). Enabling this feature is equivalent to `-warn-concurrency`, performing complete concurrency checking.
> * [SE-0352 "Implicitly Opened Existentials"](https://github.com/apple/swift-evolution/blob/main/proposals/0352-implicit-open-existentials.md) (`ImplicitOpenExistentials`) expands implicit opening to more cases in Swift 6, because we didn't want to change the semantics of well-formed code in Swift 5.x. Enabling this feature performs implicit opening in these additional cases.
> * [SE-0354 "Regex Literals"](https://github.com/apple/swift-evolution/blob/main/proposals/0354-regex-literals.md) (`BareSlashRegexLiterals`) delays the introduction of the `/.../` regex literal syntax until Swift 6. Enabling this feature is equivalent to `-enable-bare-regex-syntax`, making the `/.../` regex literal syntax available. If this proposal and SE-0354 are accepted in the same release, `-enable-bare-regex-syntax` can be completely removed in favor of this approach.

**Comment by MarcoEidinger** [comment]
I'd be interested to create a PR for the necessary HTML/JS changes.

The prerequisite for development is that https://download.swift.org/swift-evolution/proposals.json needs to be enhanced to include feature identifier information. I don't know where this JSON gets assembled. If you point me in the right direction then I might create a pull request for the same as well.

**Comment by tomerd** [comment]
cc @amartini51

**Comment by dempseyatgithub** [comment]
Thank you for submitting this issue @MarcoEidinger! The generation of the `proposals.json` file is not open source at present. The Swift Website Workgroup is investigating making this change to add the field.

When I was looking at what it would take to add the field and search to the page itself, the changes were straightforward so I put them in a PR.

I think with the changes in the PR and adding the field to the JSON file, upcoming feature flags (UFF?) would be displayed for proposals that have one and a user could search for a particular flag.

Your feature request also includes finding _all_ proposals with a feature identifier. What UI did you have in mind for that?

**Comment by MarcoEidinger** [comment]
Thank you @dempseyatgithub for creating the PR!

> Your feature request also includes finding all proposals with an upcoming feature flag. What UI did you have in mind for that?

I was thinking along the lines:

- being able to search and find proposals that have a "Feature Identifier" (a.k.a. upcoming feature flag) => website offers a filter to show only proposals with upcoming feature flags
- being able to search and find a proposal for a given Feature Identifier => search will also cover UFF and I believe the search is already on all visible properties :)

**Comment by dempseyatgithub** [comment]
This issue has four different parts:
1. Page backing data needs to include upcoming feature flags (UFFs)
2. A Proposal should display its UFF if it has one
3. User should be able to search for a particular UFF 
4. User should be able to see list of all proposals with a UFF

The existing PR works to address parts 1-3 which are essentially extensions to the existing page behavior with no change in interactive elements on the page.

Being able to filter / view a list of all proposals with a UFF is potentially more complex, so I mocked up some options.

The three options I explored:
- Magic search terms: Searching for a magic term like 'feature flags' displays proposals with UFFs
- Dedicated filter button: A button next to the filter button turns on and off a filter for proposals with UFFs
- Integrated filter: Add to the existing filter button interface for status and versions to filter for proposals with UFFs

Each section that follows has some discussions, pros and cons, and screen mockups.

# Option 1: Magic Search Terms

This option would add the ability to search for terms such as:
- ‘feature flags’
- ‘flags’
- ‘upcoming feature flags’
- ‘uff’
- ‘uffs’

This would be adding a hidden searchable property for each proposal and integrate with every other search field. Searching for 'uff' would match all proposals with upcoming feature flags, but also match all proposals with the word 'buffer' in the title.

Searching for the search terms would match any field in a proposal that contains those terms. 

## Pros:
- No additional user interface elements
- Easy to implement

## Cons:
- Not discoverable
- Search terms can potentially match other strings in proposals.
- Not guaranteed to return only proposals with UFFs.

## Mockup
![magic-search-terms@2x](https://user-images.githubusercontent.com/470139/231215816-9fa5ff33-cb20-42ad-aab5-e4b6945b0688.png)

# Option 2: Dedicated Filter Button
This option adds a dedicated filter button for proposals with an upcoming feature flag. It is additive with the status/version filter, but provides an independent interface.

## Pros:
- Very discoverable
- Simple interface with clean separation from status filters
- Highlights upcoming feature flags
- Proposal count status calls out upcoming feature flags
- Finds exact list of proposals with upcoming feature flags

## Cons:
- May give too much emphasis to upcoming feature flags

## Mockups
Displaying the dedicated filter off and on:

![dedicated-filter-off](https://user-images.githubusercontent.com/470139/231217989-4ca0c047-c4d6-4171-b65c-64e04e46f8ae.png)
![dedicated-filter-on](https://user-images.githubusercontent.com/470139/231218017-7132796d-b807-4211-a07a-c8aaa9fb43da.png)

# Option 3: Integrate with Existing Filters
This option adds a filter button for upcoming feature flags to the existing status and version filters.

## Pros:
- Finds exact list of proposals with upcoming feature flags

## Cons:
- To fit existing status/version interface, requires a relatively heavy/ungainly UI
- Awkward to fit “Upcoming Feature Flags” into existing filter status
- Not easily discoverable

## Mockups
I tried a few variations:
- A checkbox in a similar style to the existing filter buttons, in this case I did not create a new section like the 'Status' and 'Version' sections
- A filter button like the existing filter buttons, in which case a separate section seemed necessary for consistency
- Putting the checkbox at the top

![filter-page-bottom-checkbox-on](https://user-images.githubusercontent.com/470139/231222365-d3853d5b-3913-4fab-95d2-3c8136f22e7e.png)

![filter-page-top-checkbox-on](https://user-images.githubusercontent.com/470139/231222420-05868f96-c581-476f-8eb5-2b97c7949f41.png)

![filter-page-top-checkbox-off](https://user-images.githubusercontent.com/470139/231222456-90a8759d-a418-4f9c-b99e-6d55ab219c1e.png)

![filter-page-bottom-button-off](https://user-images.githubusercontent.com/470139/231222485-a6cd86e8-13ac-464d-bd7b-98c532d54885.png)

# Wrap-Up
These were the options that I was able to think of, so always welcome to additional suggestions.

Personally, Option 2, the dedicated filter button, is my preferred option. It adds a small amount of user interface, is very discoverable, and does not add to the complexity of the already complex/heavy status and version filtering UI. I think keeping the two conceptually different filters separate is better for the user experience as well as helps keep the underlying script logic less entangled and more maintainable.

**Comment by MarcoEidinger** [comment]
I like best option no 2 => Dedicated filter button (a button next to the filter button turns on and off a filter for proposals with UFFs)
