### ISSUE TITLE
Swift Programming Language book additional formats PDF, AZW & MOBI 

### ISSUE THREAD

**Issue by byaruhaf** [apple/swift-org-website#35]
### **Is your feature request related to a problem? Please describe.**
The Swift Programming Language book is the authoritative reference for Swift, offering a guided tour, a comprehensive guide, and a formal reference of the language. The problem is Not everybody is doing Swift development on Apple hardware and software. If Swift is going to be a language that is cross-platform friendly, The Swift Programming Language book needs to be as well.

### **Describe the solution you'd like**
Provide the Swift Programming Language book in additional common formats such as 
- PDF
- AZW
- MOBI 

### **Describe alternatives you've considered**
Provide links to community-generated additional formats of the Swift Programming Language book such as 
[- PDF by appsdissected](https://www.appsdissected.com/wp-content/uploads/2022/04/SwiftProgrammingLanguage56.pdf)

**Comment by TimTr** [comment]
This is a great piece of feedback. Of course we maintain the latest version of the book on the web, https://docs.swift.org/swift-book/ - but it also makes a lot of sense to add PDF, .mobi, or others. Will keep this feedback open as we are indeed looking at improvements to the Swift book, and this is a great goal to track.

Going to leave this request open

**Comment by benrimmington** [comment]
Amazon [announced](https://amzn.to/3vTqUib) that their "Send to Kindle" service will add support for EPUB (and will *drop* support for AZW and MOBI) in late 2022.

**Comment by alexandersandberg** [comment]
The Swift book is now open source! 🎉

@byaruhaf We would appreciate it if you opened a new issue on the [apple/swift-book](https://github.com/apple/swift-book) repo instead to make sure this gets to the right people. Thanks! 🙂

**Comment by byaruhaf** [comment]
Thanks @alexandersandberg, will open a new issue on the [apple/swift-book](https://github.com/apple/swift-book) repo.

**Comment by alexandersandberg** [comment]
Maybe @amartini51 can help transfer the issue even? 🙂

**Comment by amartini51** [comment]
The repository for TSPL is tracking this under https://github.com/apple/swift-book/issues/2 Add support for an offline reading experience (ePUB, PDF, etc.), so I don't think we need to transfer the issue.
