### ISSUE TITLE
Server APIs on swift.org leads to status 403 restriction

### ISSUE THREAD

**Issue by Farial-mahmod** [apple/swift-org-website#358]
Description:
Server APIs Work Group article on https://www.swift.org/blog/server-api-workgroup/ states, "....For more information, take a look at the [Server APIs project page](https://www.swift.org/server-apis/). ", whereas the URL https://www.swift.org/server-apis/ leads to a status 403 restriction.
I tried multiple times see the webpage but was restricted.

Tested On:
1. Firefox on Windows 10
2. Safari

1. Go to https://www.swift.org/blog/server-api-workgroup/
3. Before the end of the article, click on https://www.swift.org/server-apis/
4. See the issue of 403 restriction

A screenshot has been attached for better understanding.
![swift-org-403](https://github.com/apple/swift-org-website/assets/60639522/d51a0646-cc20-4fa4-807e-03fe1f02ba2e)

**Comment by alexandersandberg** [comment]
@0xTim do we redirect to https://www.swift.org/sswg/?

**Comment by 0xTim** [comment]
@alexandersandberg yeah we should either add a redirect or update the blog post with an edit note

**Comment by 0xTim** [comment]
Added a PR to update it - will need a blog code owner to merge
