### ISSUE TITLE
Swift on Server/guides/allocation is totally mangled and missing content

### ISSUE THREAD

**Issue by weissi** [apple/swift-org-website#364]
## Describe the bug

The original article https://github.com/swift-server/guides/blob/main/docs/allocations.md was republished as https://www.swift.org/server/guides/allocations.html but unfortunately it doesn't render properly

## To Reproduce

- Try to read the full article
- Try to see the images
- 
## Expected behavior

- Full article readable
- Images available
 
## Actual behavior

- A lot of missing content / images
- A lot seems to be (in unreadable form) under the "Demo program source code" disclosure triangle

**Comment by tomerd** [comment]
cc @0xTim

**Comment by natikgadzhi** [comment]
Looks like to make <details> block work like in gh-flavored markdown, we'd have to use https://github.com/github/jekyll-commonmark-ghpages. Which could have side effects for other pages. 

So it might be easier to just expand the details block and let it be. I'll try to put up a fix in a bit.
