### ISSUE TITLE
Swift 5.0 release entry is duplicated

### ISSUE THREAD

**Issue by soumyamahunt** [apple/swift-org-website#391]
## Describe the bug

In the older releases section Swift 5.0 release entry is duplicated.

## To Reproduce

1. Go to [download page](https://www.swift.org/download/).
2. Expand older releases.
3. Scroll down to Swift 5.0 release.
4. See error.

## Expected behavior

Only 1 entry should be present per release.

## Actual behavior

Swift 5.0 release entry duplicated.

## Screenshots

<img width="1150" alt="Screenshot 2023-09-10 at 2 49 43 AM" src="https://github.com/apple/swift-org-website/assets/51203900/1a8d01fb-6a3e-42da-b2ee-901c063f305f">

### Desktop (please complete the following information):

- OS: macOS
- Browser chrome
- Version 116.0.5845.140

Applicable to all browser and os.

## Additional context

This could be related to duplicate entries in [swift_releases.yml](https://github.com/apple/swift-org-website/blob/main/_data/builds/swift_releases.yml):

https://github.com/apple/swift-org-website/blob/52f9974d3f395099624419cd2fa2bdd30af28a1a/_data/builds/swift_releases.yml#L280-L313

**Comment by alexandersandberg** [comment]
Closing as this is fixed in #392. Thanks for reporting!
