### ISSUE TITLE
Conflict with post permalinks when generating the site

### ISSUE THREAD

**Issue by daveverwer** [apple/swift-org-website#41]
There are currently two conflicting post URLs for these two blog posts:

* `_posts/2019-10-31-sswg-update.md`
* `_posts/2022-04-19-sswg-update.md`

This generates a warning (see below) when generating the site, but it also means that the old 2019 post by Tanner on the live site now links to the new post by Tim.

The warning:

```
$ LC_ALL=en_us.UTF-8 be jekyll serve
Configuration file: /Users/dave/Developer/SwiftOrgWebsite/_config.yml
            Source: /Users/dave/Developer/SwiftOrgWebsite
       Destination: /Users/dave/Developer/SwiftOrgWebsite/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /Users/dave/Developer/SwiftOrgWebsite/_site/blog/sswg-update/index.html
                     - /Users/dave/Developer/SwiftOrgWebsite/_posts/2019-10-31-sswg-update.md
                     - /Users/dave/Developer/SwiftOrgWebsite/_posts/2022-04-19-sswg-update.md
                    
                    done in 1.618 seconds.
 Auto-regeneration: enabled for '/Users/dave/Developer/SwiftOrgWebsite'
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
```

This issue has the effect of completely removing the older post from the live site, so any external links to that post now point at the new one.

To fix it without too much disruption, I would suggest that we rename the 2019 post file to `_posts/2019-10-31-sswg-update-2019.md`, which gives it the URL `blog/sswg-update-2019/` and leave the 2022 post alone. There are more likely to be recent links to that post using that URL, and breaking the permalink so soon after publishing isn’t great.

I have this change made locally on a branch if you’d like me to put it in as a PR.

I wonder if we could also update CI to check for this conflict warning so that this doesn’t happen again accidentally.

**Comment by 0xTim** [comment]
+1 to updating the old URL and +1 to failing CI if we get warnings like this

**Comment by tomerd** [comment]
+1
