### ISSUE TITLE
https://swift.org/getting-started/#using-the-package-manager became a dead link in the website redesign

### ISSUE THREAD

**Issue by neonichu** [apple/swift-org-website#420]
https://swift.org/getting-started/#using-the-package-manager is linked from SwiftPM's documentation and also at least one other page on swift.org itself, but became a dead link, probably during the redesign. It just brings you to the main getting starting page now.

It should probably redirect to https://www.swift.org/getting-started/cli-swiftpm/ where similar docs to the old "getting started" live now.

**Comment by alexandersandberg** [comment]
Thanks! I have opened a PR: https://github.com/apple/swift-org-website/pull/421.
