### ISSUE TITLE
Add checking for conflicting URLs to CI

### ISSUE THREAD

**Issue by daveverwer** [apple/swift-org-website#44]
As mentioned in #41, it might be good for the CI to check for the warning message when Jekyll spots a conflicting URL. I just checked, and the `jekyll build` command does not return an error code in this situation, so we may need to resort to checking the output of the build command, which looks something like this:

```
Conflict: The following destination is shared by multiple files.
		The written file may end up with unexpected contents.
		/Users/dave/Developer/SwiftOrgWebsite/_site/blog/sswg-update/index.html
		 - /Users/dave/Developer/SwiftOrgWebsite/_posts/2019-10-31-sswg-update.md
		 - /Users/dave/Developer/SwiftOrgWebsite/_posts/2022-04-19-sswg-update.md
```

To reproduce this, there is a duplicate post in commit 48c41a8be659aaa29273a22459f280d4ed6c6a18 (and others, but it's definitely there in that one).

**Comment by tomerd** [comment]
@shahmishal can we teach the CI job / build script to fail on these?

**Comment by shahmishal** [comment]
Going to use `jekyll doctor` to catch these type of issues in the future.
