### ISSUE TITLE
Swift Evolution search input field is broken

### ISSUE THREAD

**Issue by MaxDesiatov** [apple/swift-org-website#440]
## Describe the bug

Search input field at https://www.swift.org/swift-evolution/ no longer works.

## To Reproduce

1. Navigate to https://www.swift.org/swift-evolution/;
2. Move input focus to the search field;
3. Type any text.

## Expected behavior

Evolution proposals filtered by a simple substring match are displayed.

## Actual behavior

The list of evolution proposals doesn't change at all.

## Screenshots

<img width="683" alt="Screenshot 2023-11-07 at 15 03 37" src="https://github.com/apple/swift-org-website/assets/112310/cbd23234-66fa-45a9-aaef-4c46b96ddc21">

### Desktop (please complete the following information):

- OS: macOS Sonoma
- Browser: tried Safari 17 and Firefox 119

### Swift.org version/commit hash

[1cace59](https://github.com/apple/swift-org-website/commit/1cace59e070433ab7943d3df3c946ef171b07dbb)

**Comment by dempseyatgithub** [comment]
I am able to reproduce this in Firefox 119.0 and 119.0.1.
I am not able to reproduce it in Safari 17.1.
I am also not able to reproduce it in Chrome 118.0.5993.117.

This is on macOS 14.1.

@MaxDesiatov Are you on Safari 17.0 and macOS 14.0?

Looking for the discrepancy in reproducing this.

**Comment by MaxDesiatov** [comment]
I'm on macOS 14.2 beta with whatever Safari version comes included.

**Comment by dempseyatgithub** [comment]
This is not reproducing for me on the latest Chrome 119.0.6045.105.

**Comment by dempseyatgithub** [comment]
I am able to reproduce in Safari Technology Preview
Release 182 (Safari 17.4, WebKit 19618.1.4.1)

**Comment by dempseyatgithub** [comment]
> I'm on macOS 14.2 beta with whatever Safari version comes included.

Thanks, then it is likely the same issue I am seeing in the Safari Technology Preview.

**Comment by dempseyatgithub** [comment]
The search field element is being found and the event listener is being attached.

**Comment by dempseyatgithub** [comment]
The search field is using the non-standard ‘search’ event for its event listener. It looks like we should be using ‘input’ instead.

It looks like this was removed from WebKit with this commit:
[Remove incremental attribute and search event](https://github.com/WebKit/WebKit/commit/99ff08340f12db8d867a0ed04f176802b7e0a355)

According to MDN, it looks like this event was never supported in Firefox:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/search_event

It also looks like the `incremental` attribute is deprecated and can be removed.

I should have a PR with a fix shortly after I do some testing first.

**Comment by dempseyatgithub** [comment]
Thank you for reporting this @MaxDesiatov! It should be working for you now.

**Comment by MaxDesiatov** [comment]
I can confirm it's fixed, thanks for the prompt response!
