### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by interrealm** [apple/swift-org-website#490]
## Describe the bug

At https://www.swift.org/documentation/ in the Contributing section, the description of Swift Evolution has misspelled 'language' as 'langague'

## Screenshots
<img width="890" alt="issue" src="https://github.com/apple/swift-org-website/assets/117502202/7e22c568-bd0a-4964-a86a-491f98d46e7a">

**Comment by alexandersandberg** [comment]
Thanks! There's a PR open to fix it.
