### ISSUE TITLE
swift.org/download no longer reachable

### ISSUE THREAD

**Issue by MaxDesiatov** [apple/swift-org-website#494]
## Describe the bug

Previously, https://swift.org/download page was reachable from the index page of https://swift.org. Now, apparently the only way to reach it is to open https://swift.org/download URL directly.

## To Reproduce

1. Navigate to https://swift.org
2. Try to find a link that leads to https://swift.org/download, where different versions of toolchains are available.

## Expected behavior

A link to https://swift.org/download can be easily found.

## Actual behavior

No such link is available.

### Swift.org version/commit hash

7bec5d8

## Additional context

Downloading different versions of the Swift toolchain is an important workflow, which became much more difficult to follow with the latest redesign.

**Comment by alexandersandberg** [comment]
Thanks! We've identified this as well and will discuss the best solution in the next SWWG meeting.

**Comment by shahmishal** [comment]
https://github.com/apple/swift-org-website/pull/512
