### ISSUE TITLE
Show current page in nav bar

### ISSUE THREAD

**Issue by rauhul** [apple/swift-org-website#502]
The top navigation bar doesn't indicate the current page well, for example if you go to "blog", after navigating to the page, it is not visually different from the other links.

Current:
<img width="1199" alt="Screenshot 2024-01-28 at 4 06 48 PM" src="https://github.com/apple/swift-org-website/assets/9739930/2cb76ac7-cd2f-4329-b0db-7c4328e85069">

Ideally:
<img width="1245" alt="Screenshot 2024-01-28 at 4 06 54 PM" src="https://github.com/apple/swift-org-website/assets/9739930/1c2824cb-fe6d-4c63-9e98-8b630ef8b9f6">

I started implementing this on branch `nav-select` but was unsure how to handle laying out text such that the bold affect didn't cause text to jump

**Comment by rauhul** [comment]
@kaishin do you have ideas on how to do this? I started on `nav-select` but I dont really understand a web-isms and got stuck trying to get everything to layout properly.

**Comment by kaishin** [comment]
@rauhul There are techniques to avoid the text jump, but they almost always involves using flex or grid. Flex should work here but would require some testing. Details of the approach I have in mind can be found [here](https://css-tricks.com/bold-on-hover-without-the-layout-shift/).

Alternatively we can only do with a color change for now, to simplify things.

**Comment by Codermex-freelance** [comment]
Hola que tal, necesitas que se cambie de color cuando selecciones un menú de la barra de navegación?

**Comment by federicobucchi** [comment]
This has been added - @rauhul please verify

**Comment by rauhul** [comment]
> This has been added - @rauhul please verify

it works half correctly, the navigation items expand on selection which doesn't look very nice. The items shouldn't jump after changing pages

**Comment by federicobucchi** [comment]
@rauhul I made this PR for the text shifting: https://github.com/apple/swift-org-website/pull/610

**Comment by federicobucchi** [comment]
@rauhul this got closed automatically because I merged the PR.  Please let me know if you notice something and this needs to be re-opened!
