### ISSUE TITLE
Proposal 422 has unexpected status

### ISSUE THREAD

**Issue by MahdiBM** [apple/swift-org-website#505]
Not a big deal, but:

The proposal [#422](https://github.com/apple/swift-evolution/blob/main/proposals/0422-caller-side-default-argument-macro-expression.md) uses `Awaiting Review` as it's status, which is new.

We already have `Scheduled For Review`, so not sure if introducing `Awaiting Review` was actually intended.

Considering the other issues i've filed (#489, #504), it feels like https://github.com/apple/swift-evolution needs a validation CI. 
Perhaps just re-create the JSON and make sure there are no 'errors'. In which case the json-creation script might want to be more strict about the statuses.

**Comment by dempseyatgithub** [comment]
`Awaiting Review` is a valid status. It is not used very often however.

> Considering the other issues i've filed (https://github.com/apple/swift-org-website/issues/489, https://github.com/apple/swift-org-website/issues/504), it feels like https://github.com/apple/swift-evolution needs a validation CI.

Agreed. There are some efforts underway around this.
