### ISSUE TITLE
Missing implementation links for evolution proposal

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift-org-website#537]
## Describe the bug

I've noticed that some proposals are missing fields, but I cannot figure out why.

## To Reproduce

SE-0420 is missing the implementation field, but SE-0418 is not.

## Expected behavior

I would assume SE-0420 would have links to the implementation PRs too.

## Actual behavior

No links!

### Desktop (please complete the following information):

Safari on macOS 14.2.1 (23C71)

**Comment by alexandersandberg** [comment]
Thanks for reporting this!

It seems like the `implementation` array is missing from the source file for SE-0410, SE-0420, SE-0421, and possibly more.

cc: @amartini51

**Comment by dempseyatgithub** [comment]
Hey @alexandersandberg! I'm in the process of writing a modernized version of the tool that extracts the metadata from the proposals, so you can feel free to cc: me in the future.

It looks like the existing tool does not parse bare implementation URLs, so these are not being found and reported.

The short term fix would be to add the full link to these proposals.
For example:
```
[apple/swift#14586](https://github.com/apple/swift/pull/14586)
```

The medium term fix will be to have the modern version of the tool  (hopefully soon to be deployed) recognize and extract the bare URLs.
