### ISSUE TITLE
Stray space before commas in SSWG lists

### ISSUE THREAD

**Issue by amartini51** [apple/swift-org-website#558]
## Describe the bug

The [SSWG page](https://www.swift.org/sswg/) has a list of current and past members.  Each name has a space on both sides of the comma.  For example, the first item with a comma is:

> Franz Busch , Apple

## Screenshots

<img width="660" alt="image" src="https://github.com/apple/swift-org-website/assets/15617351/5586cca8-384d-400c-9888-65fcb3da7e53">

### Swift.org version/commit hash

9da7f982d9639a82527a9c94309e7af10577ce4c

## Additional context

I believe the following change would remove the stray spaces, but I'm not set up to test it locally:

```diff
diff --git sswg/index.md sswg/index.md
index cc97c74a..a8c45c9a 100644
--- sswg/index.md
+++ sswg/index.md
@@ -18,7 +18,7 @@
 {% for person in people %}
 <li> {{ person.name }}
 {% if person.affiliation %}
-  , {{ person.affiliation }}
+, {{ person.affiliation }}
 {% endif %}
 {% if person.github %}
   (<a href="https://github.com/{{person.github}}">@{{person.github}}</a>)
@@ -34,7 +34,7 @@
 {% for person in people %}
 <li> {{ person.name }}
 {% if person.affiliation %}
-  , {{ person.affiliation }}
+, {{ person.affiliation }}
 {% endif %}
 {% if person.github %}
   (<a href="https://github.com/{{person.github}}">@{{person.github}}</a>)
```

**Comment by alexandersandberg** [comment]
Thanks, Alex! I've opened a PR to fix this. 🙂
