### ISSUE TITLE
Missing webrick?

### ISSUE THREAD

**Issue by lexrus** [apple/swift-org-website#6]
Installed ruby via rbenv.
```
rbenv versions
  system
* 3.0.2 (set by /Users/lex/.rbenv/version)
```
Then `bundle install` without errors.

It failed to run `LC_ALL=en_us.UTF-8 bundle exec jekyll serve`:
```servlet.rb:3:in require': cannot load such file -- webrick (LoadError)```

<details>
<summary>Error output</summary>
bash
Configuration file: /Users/lex/g/swift-org-website/_config.yml
            Source: /Users/lex/g/swift-org-website
       Destination: /Users/lex/g/swift-org-website/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 1.477 seconds.
 Auto-regeneration: enabled for '/Users/lex/g/swift-org-website'
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `require_relative'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `setup'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:100:in `process'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
	from /Users/lex/.rbenv/versions/3.0.2/bin/jekyll:23:in `load'
	from /Users/lex/.rbenv/versions/3.0.2/bin/jekyll:23:in `<top (required)>'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli.rb:484:in `exec'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/cli.rb:25:in `start'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/exe/bundle:48:in `block in <top (required)>'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/lex/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.3.8/exe/bundle:36:in `<top (required)>'
	from /Users/lex/.rbenv/versions/3.0.2/bin/bundle:23:in `load'
	from /Users/lex/.rbenv/versions/3.0.2/bin/bundle:23:in `<main>'
</details>

Once I add webrick with bundle everything works great.
`bundle add webrick`

**Comment by shahmishal** [comment]
I have not tried ruby 3.0.2 with swift-org-website, CI is using ruby 2.6. Let's keep this bug open and figure out what's need it to upgrade to ruby 3.0.2.

**Comment by stevapple** [comment]
@shahmishal Ruby 3 removed `webrick` from the standard libraries, so it needs to be installed manually.
