### ISSUE TITLE
Commit #e1ebe463 breaks Swift Evolution dashboard author layout

### ISSUE THREAD

**Issue by dempseyatgithub** [apple/swift-org-website#636]
It looks like #543 breaks the layout of authors on the Swift Evolution dashboard.

<img width="1024" alt="Screenshot 2024-04-11 at 10 35 55 AM" src="https://github.com/apple/swift-org-website/assets/470139/4b644781-ca7c-456c-91f8-3016474dc379">

A lot of additional space is added around the authors for each proposal.

**Comment by alexandersandberg** [comment]
Good catch, James! A PR is open.
