### ISSUE TITLE
Platforms Steering Group and 

### ISSUE THREAD

**Issue by parispittman** [apple/swift-org-website#638]
## Describe the bug

Platforms Steering Group and Contributor Experience Workgroup are missing from the Community Structure list. https://www.swift.org/community/ (scroll to Community Structure) 

https://www.swift.org/platform-steering-group/ - link for the Platforms Steering Group
https://www.swift.org/contributor-experience-workgroup/ - contributor experience workgroup  

Good issue for someone looking to get a PR in :)

**Comment by louisunlimited** [comment]
@parispittman Hi can I work on this! Thanks

**Comment by alexandersandberg** [comment]
Closing this as it's done, thanks!
