### ISSUE TITLE
Latest main snapshots not published for Ubuntu 18.04

### ISSUE THREAD

**Issue by patrickfreed** [apple/swift-org-website#647]
## Describe the bug

It looks like the main snapshots for Ubuntu 18.04 have lagged behind the other platforms. The latest one published for 18.04 as of filing this issue was on April 13th, whereas all of the other platforms have had them published as recent as April 21st. Is this intentional?

### Swift.org version/commit hash

e.g. swift-ci didn't publish anything for 18.04 in this commit: https://github.com/apple/swift-org-website/commit/064f3890daaecc24e7d13c3803033bad096827be

**Comment by 0xTim** [comment]
I believe this is intentional because 18.04 is EOL this month so by the time the next release is cut from main it will no longer be supported

**Comment by 0xTim** [comment]
Correction it was EOLed a year ago

**Comment by shahmishal** [comment]
This is expected, as we dropped support for Ubuntu 18.04 for main and release/6.0 branch.  https://forums.swift.org/t/dropping-support-for-ubuntu-18-04/69561

**Comment by patrickfreed** [comment]
makes sense, thanks!
