### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by victormicco** [apple/swift-org-website#663]

**Comment by 0xTim** [comment]
@victormicco Were there specific areas that are causing issues? The site should work fine with screen readers and other assistive technologies, but it's possible we might have a bug in some places

**Comment by victormicco** [comment]
@0xTim 
The flow of the elements seems not that great for ppl with disabilities, I mean like, the Navbar, stays on the last position of the queue when I have to press tab for example to find something, but a user actually needs to know the sections of an website and choose the one he wants, but in the currently flow, the user has to see all the page before choose where he wanna go.
Maybe thats too much, but I really think it would improve this project.

But its not Bugs, just flow issues to some people.
