### ISSUE TITLE
Migrate apple/swift-internals repository into apple/swift-org-website

### ISSUE THREAD

**Issue by shahmishal** [apple/swift-org-website#68]
Now Swift.org website is open source, we should migrate apple/swift-internals into apple/swift-org-website.

 - [x] Migrate the [index.md](https://github.com/apple/swift-internals/blob/gh-pages/api-design-guidelines/index.md) file to `documentation/api-design-guidelines`
 - [x] Review and migrate the GitHub Issues from apple/swift-internals over to apple/swift-org-website
 - [x] Update the swift.org deployment (remove the swift-internals)
 - [x] Archive the apple/swift-internals repository

**Comment by shahmishal** [comment]
https://github.com/apple/swift-org-website/pull/69

**Comment by shahmishal** [comment]
Repository now archived.

**Comment by alexandersandberg** [comment]
@shahmishal It might be a good idea to update the [apple/swift-internals README](https://github.com/apple/swift-internals#readme) with a note saying that it has been merged into this repo and issues and PRs can be opened here instead.

Just in case people still end up at the old repo wanting to contribute.

**Comment by shahmishal** [comment]
Repo is marked `This repository has been archived by the owner. It is now read-only.`. Let me see if we can revert the archived step, and modify the README.

**Comment by alexandersandberg** [comment]
Yes, I was just thinking of the scenario where there might be a link to the old repo without any mention of the new repo. Then they would only see that it's archived, but not know where to go instead. 🙂

**Comment by shahmishal** [comment]
@alexandersandberg Updated the README, let me know if I missed anything. thanks!

**Comment by alexandersandberg** [comment]
@shahmishal Looks great, thank you! 🙂
