### ISSUE TITLE
Some older evolution protocols still just "accepted"

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift-org-website#700]
## Describe the bug

The following proposals are currently "Accepted", but I *think* they are all actually implemented?

SE-0246
SE-0283
SE-0321
SE-0342
SE-0387

## To Reproduce

Filter evolution proposals by "Accepted"

## Expected behavior

Filter out implemented proposals.

## Actual behavior

These 5 still show up.

### Desktop (please complete the following information):

- OS: macOS
- Browser: Safari
- Version: 17.4.1

### If possible, minimal yet complete reproducer code (or link to code)

https://www.swift.org/swift-evolution/#?status=accepted

**Comment by alexandersandberg** [comment]
We extract this data from the https://github.com/apple/swift-evolution repo (and it looks like this is not a data extraction issue), so it would be better to open a PR there. 🙂

@shahmishal maybe you can move this issue over?

**Comment by dempseyatgithub** [comment]
The proposals in the `swift-evolution` repository are the source of truth for the dashboard.

@mattmassicotte If you are willing, the quickest resolution would be to submit a PR to `swift-evolution` updating the status field of those proposals.

I've been doing a lot of cleanup and normalizing of proposal metadata, so if you aren't able to get to it, I can do that post-WWDC.

**Comment by mattmassicotte** [comment]
Thanks everyone, the problem now makes sense!

I'll close and look at it on that end.
