### ISSUE TITLE
Install Page: Automatically select single Linux platform version

### ISSUE THREAD

**Issue by dempseyatgithub** [apple/swift-org-website#710]
When a Linux platform only has one version, the user still needs to select a version to see the details.

If there is only one version for a platform, the version should be selected automatically, so clicking the platform displays the single selected version and the install instructions.

Otherwise the user needs to press the one button to get the directions to appear:
<img width="906" alt="Screenshot 2024-06-10 at 7 09 54 AM" src="https://github.com/apple/swift-org-website/assets/470139/eb0735ed-4c2c-4fa9-b804-c5f2c9df70a9">

**Comment by alexandersandberg** [comment]
See #709

**Comment by dempseyatgithub** [comment]
Yes, that PR should definitely close this issue. Unfortunately, I won't have time to review that PR until after WWDC, it's already an over-packed week.
